config/routes.rb
Rails.application.routes.draw do
  resources :class_rooms

end

app/models/class_room.rb
class ClassRoom < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/class_rooms_controller.rb
class ClassRoomsController < ApplicationController
  before_action :set_class_room, only: [:show, :edit, :update, :destroy]


  # GET /class_rooms
  # GET /class_rooms.json
  def index
    @class_rooms = ClassRoom.all
  end

  # GET /class_rooms/1
  # GET /class_rooms/1.json
  def show
  end

  # GET /class_rooms/new
  def new
    @class_room = ClassRoom.new
  end

  # GET /class_rooms/1/edit
  def edit
  end

  # POST /class_rooms
  # POST /class_rooms.json
  def create
    @class_room = ClassRoom.new(class_room_params)

    #use service objects here
    service = ClassRoomMathService.new(@class_room)
    if service.perform

      if service.success?
        if @class_room.save
          redirect_to class_room_path(@class_room)
        end
      else
        flash[:error] = "Too many!"
        render "new"
      end
      
    end

  end

  # PATCH/PUT /class_rooms/1
  # PATCH/PUT /class_rooms/1.json
  def update
    respond_to do |format|
      if @class_room.update(class_room_params)
        format.html { redirect_to @class_room, notice: 'Class room was successfully updated.' }
        format.json { render :show, status: :ok, location: @class_room }
      else
        format.html { render :edit }
        format.json { render json: @class_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /class_rooms/1
  # DELETE /class_rooms/1.json
  def destroy
    @class_room.destroy
    respond_to do |format|
      format.html { redirect_to class_rooms_url, notice: 'Class room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_class_room
      @class_room = ClassRoom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def class_room_params
      params.require(:class_room).permit(:boys, :girls, :teachers)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/class_rooms_helper.rb
module ClassRoomsHelper
end

app/views/class_rooms/_form.html.erb
<%= form_for(@class_room) do |f| %>
  <% if @class_room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@class_room.errors.count, "error") %> prohibited this class_room from being saved:</h2>

      <ul>
      <% @class_room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :boys %><br>
    <%= f.number_field :boys %>
  </div>
  <div class="field">
    <%= f.label :girls %><br>
    <%= f.number_field :girls %>
  </div>
  <div class="field">
    <%= f.label :teachers %><br>
    <%= f.number_field :teachers %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/class_rooms/edit.html.erb
<h1>Editing class_room</h1>

<%= render 'form' %>

<%= link_to 'Show', @class_room %> |
<%= link_to 'Back', class_rooms_path %>

app/views/class_rooms/index.html.erb
<h1>Listing class_rooms</h1>

<table>
  <thead>
    <tr>
      <th>Boys</th>
      <th>Girls</th>
      <th>Teachers</th>
      <th>Total</th>
      <th>Students</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @class_rooms.each do |class_room| %>
      <tr>
        <td><%= class_room.boys %></td>
        <td><%= class_room.girls %></td>
        <td><%= class_room.teachers %></td>
        <td><%= class_room.total %></td>
        <td><%= class_room.students %></td>
        <td><%= link_to 'Show', class_room %></td>
        <td><%= link_to 'Edit', edit_class_room_path(class_room) %></td>
        <td><%= link_to 'Destroy', class_room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Class room', new_class_room_path %>

app/views/class_rooms/new.html.erb
<h1>New Class Room!!!!!!!!!</h1>

<%= render 'form' %>

<%= link_to 'Back', class_rooms_path %>

app/views/class_rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Boys:</strong>
  <%= @class_room.boys %>
</p>

<p>
  <strong>Girls:</strong>
  <%= @class_room.girls %>
</p>

<p>
  <strong>Teachers:</strong>
  <%= @class_room.teachers %>
</p>

<p>
  <strong>Total:</strong>
  <%= @class_room.total %>
</p>

<p>
  <strong>Students:</strong>
  <%= @class_room.students %>
</p>

<%= link_to 'Edit', edit_class_room_path(@class_room) %> |
<%= link_to 'Back', class_rooms_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Classroom</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>